# Generated by Django 2.2.2 on 2019-07-02 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='Stdent Name')),
                ('department', models.CharField(blank=True, choices=[('CSE', 'Computer Science'), ('ISE', 'Information Science')], max_length=30, null=True, verbose_name='Department')),
            ],
        ),
    ]
