# Generated by Django 2.2.2 on 2019-07-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USN', models.CharField(max_length=30, unique=True, verbose_name='U S N')),
                ('sem', models.IntegerField(verbose_name='Semester')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('cgpa', models.FloatField(verbose_name='CGPA')),
            ],
        ),
    ]
