# Generated by Django 2.2.2 on 2019-07-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190702_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science'), ('ISE', 'Information Science')], max_length=30, null=True, verbose_name='Name'),
        ),
    ]
