# Generated by Django 2.2.2 on 2019-07-02 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190702_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20, verbose_name='firstname')),
                ('lastname', models.CharField(default='', max_length=20, null=True, verbose_name='lastname')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Section_name', models.CharField(max_length=10, verbose_name='Sect_name')),
                ('Advisor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Employee')),
                ('students', models.ManyToManyField(to='home.Student')),
            ],
        ),
    ]
