# Generated by Django 2.2.2 on 2019-07-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_employee_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='profile',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
