# Generated by Django 2.2.2 on 2019-07-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_details_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='profile',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='profile'),
        ),
    ]
